packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - next@16.0.10
  - "@next/*"
  - react
  - react-dom

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - prisma
