import type { Metadata } from "next";
import "@ascnd-gg/ui/globals.css";
import { ThemeToggle } from "../components/theme-toggle";
import Providers from "../components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          {children}
          <footer className="container">
            <ThemeToggle />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
